### ISSUE TITLE
Font-awesome and Office UI Fabric not working with stencil 1.13

### ISSUE THREAD

**Issue by EddieGr** [drygnet/stenciljs-icons-example#1]
It seems like stencil core version 1.13 shows blank images on Font-awesome and Office UI Fabric images.
![image-blank](https://user-images.githubusercontent.com/61042597/82783580-0c14e880-9e5f-11ea-9810-bb095aa5bc29.png)

**Repro steps:**
Clone repo: git clone https://github.com/drygnet/stenciljs-icons-example.git 
npm install && npm start
//This works, all images shows correctly.

//But if you remove package-lock.json and retry, it doesn't work:
rm -rf node_modules && rm package-lock.json
npm i && npm start
//package-lock.json now shows updated stencil-core version and images shows incorrectly.
![image](https://user-images.githubusercontent.com/61042597/82783953-de7c6f00-9e5f-11ea-84b5-47cc8173bdf9.png)

It might just be a version issue, how can this be resolved?

**Comment by drygnet** [comment]
StyleUrls-array in component was ignored, solved by adding the font-css as an import in the components CSS (not a bad thing, actually better) should work now.

**Comment by grootendorsteduard** [comment]
@drygnet I realized that the styleUrls only used the first one so I just used styleUrl but that didn't solve my issue. Can you show me what you mean by your previous comment, I'm not sure how you fixed it?

**Comment by EddieGr** [comment]
@drygnet thank you. Just to clarify. I changed styleUrls to styleUrl: './fontawesome.css' (which points to the component's stylesheet) and inside fontawesome.css at the top I added @import '../../assets/fontawesome/css/all.min.css';

This worked. Thank you.

**Comment by drygnet** [comment]
the repo is updated with working version
